openapi: 3.0.2
info:
  title: Greeting Service
  version: 1.0
  description: API definition of Catalog Service
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /api/greetings/{username}:
    get:
      parameters:
        - name: username
          description: new user name
          schema:
            type: string
          in: path
          required: true
          examples:
            Username1:
              value: Username1
            Username2:
              value: Username2
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
              examples:
                Username1:
                  value:
                    id: 1
                    uui: 86c790b1-19be-41c1-bf38-d22c6fe2ced1
                    username: Vizier
                Username2:
                  value:
                    id: 2
                    uui: 103fc1ea-ab5f-476e-88fa-5bfaeb11c06a
                    username: Ivorjour
components:
  schemas:
    Greeting:
      title: Root Type for Greeting
      type: object
      properties:
        id:
          description: Unique identifier of this greeting
          type: number
        uui:
          description: UUID for this greeting
          type: string
        username:
          description: Users Name for this greeting
          type: string
      required:
        - id
        - uui
        - username
      additionalProperties: false
