openapi: 3.0.2
info:
  title: Greetings Service
  version: 1.0
  description: API definition of Catalog Service
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /api/greetings/{username}:
    get:
      parameters:
        - name: username
          description: new user name
          schema:
            type: string
          in: path
          required: true
          examples:
            Username1:
              value: Username1
            Username2:
              value: Username2
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Greeting"
              examples:
                Username1:
                  value:
                    id: 1
                    username: Vizier
                Username2:
                  value:
                    id: 2
                    username: Victor
        "500":
          content:
            application/json:
              schema:
                type: string
              examples:
                Username1:
                  value: ""
components:
  schemas:
    Greeting:
      title: Root Type for Greeting
      type: object
      properties:
        username:
          description: Users Name for this greeting
          type: string
      required:
        - username
      additionalProperties: false
